name: Deployment - Reusable Workflow

on:
    workflow_call:
        inputs:
          mongodb-uri:
            required: true
            type: string
          kubectl-version:
            description: Provide the Kubectl version
            required: true
            type: string
            default: v1.27.0
          k8s-manifest-dir:
            description: Directory Containing Kubernetes Manifests
            required: true
            type: string
            default: kubernetes/
          environment:
            description: Provide the development Environment
            default: dev
            required: true
            type: string
        secrets:
          k8s-kubeconfig:
            required: true
          mongodb-password:
            required: true
        outputs:
            application-url:
                value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}

jobs:
   reuse-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{  inputs.environment }}
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Kubectl CLI install
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
        
      - name: Set Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
            method: kubeconfig
            kubeconfig: ${{ secrets.k8s-kubeconfig }}

      - name: Fetch Kubernetes Cluster Details
        run: |
            kubectl version --short
            echo ------------------------------
            kubectl get nodes
      - name: Save Nginx Ingress Controller IP as GITHUB Environment Variable
        run: |
              echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadbalancer.ingress[0].ip}")" >> $GITHUB_ENV
      - name: Replace token on manifest file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{ inputs.k8s-manifest-dir }}*.yml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          # k -n ingress-nginx get svc ingress-nginx-controller
          INGRESS_IP: ${{ env.INGRESS_IP }}
      
      - name: Check files
        run: |
          cat ${{ inputs.k8s-manifest-dir }}*.yml

      - name: Create Mongodb Secrets
        run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ inputs.mongodb-uri }} \
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
      
      - name: Deploy to Dev Env
        run: |
              kubectl apply -f ${{ inputs.k8s-manifest-dir }}
      - name: Set App Ingress Host URL
        id: set-ingress-host-address
        run: |
              echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"